In [1]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

In [2]:
ookla_df = pd.read_csv('F:\Economic2019\Ookla_Merged.csv')

ookla_df

<>:1: SyntaxWarning: invalid escape sequence '\E'
<>:1: SyntaxWarning: invalid escape sequence '\E'
C:\Users\Omar\AppData\Local\Temp\ipykernel_13348\3034195625.py:1: SyntaxWarning: invalid escape sequence '\E'
  ookla_df = pd.read_csv('F:\Economic2019\Ookla_Merged.csv')

,avg_d_kbps,avg_u_kbps,avg_lat_ms,tests,devices,geometry
0,4100.250000,1852.5000,26.500000,1,1,"POLYGON ((-160.02685546875 70.6435894914449, -..."
1,9195.000000,3347.0000,43.000000,1,1,"POLYGON ((-160.032348632812 70.6399478155463, ..."
2,1898.125000,878.0625,11.187500,2,1,"POLYGON ((-160.043334960938 70.6363054807905, ..."
3,7384.000000,3868.0000,65.000000,1,1,"POLYGON ((-160.037841796875 70.6363054807905, ..."
4,8895.000000,3429.0000,43.000000,2,2,"POLYGON ((-160.02685546875 70.6417687358462, -..."
...,...,...,...,...,...,...
9059732,5461.333333,1559.0000,20.777778,1,1,"POLYGON ((169.469604492188 -46.5588603031172, ..."
9059733,179.500000,247.0000,7.500000,1,1,"POLYGON ((169.579467773438 -46.5626373208684, ..."
9059734,4859.666667,2125.0000,15.000000,1,1,"POLYGON ((170.194702148438 -46.0732306254084, ..."
9059735,2115.250000,1121.1875,2.937500,3,2,"POLYGON ((170.194702148438 -46.0770413127077, ..."
9059736,5222.000000,5880.5000,6.500000,1,1,"POLYGON ((3.394775390625 -80.6880109730487, 3...."

In [3]:
Viirs = pd.read_csv('F:\Economic2019\Viirs_Merged_Cleaned.csv')

Viirs

<>:1: SyntaxWarning: invalid escape sequence '\E'
<>:1: SyntaxWarning: invalid escape sequence '\E'
C:\Users\Omar\AppData\Local\Temp\ipykernel_13348\431903740.py:1: SyntaxWarning: invalid escape sequence '\E'
  Viirs = pd.read_csv('F:\Economic2019\Viirs_Merged_Cleaned.csv')

         longitude   latitude  light_intensity
0       -53.133333 -22.645834         0.001105
1       -53.133333 -22.641667         0.001325
2       -53.133333 -22.637500         0.001348
3       -53.129167 -22.650000         0.001204
4       -53.129167 -22.645834         0.001163
...            ...        ...              ...
4219474 -37.354166 -11.595833         0.001277
4219475 -37.354166 -11.591667         0.001217
4219476 -37.354166 -11.587500         0.001300
4219477 -37.354166 -11.583333         0.001065
4219478 -37.354166 -11.579167         0.000961

[4219479 rows x 3 columns]

In [4]:
# Convert Ookla geometry to GeoDataFrame
ookla_df['geometry'] = ookla_df['geometry'].apply(wkt.loads)
ookla_df = gpd.GeoDataFrame(ookla_df, geometry='geometry')

ookla_df

,avg_d_kbps,avg_u_kbps,avg_lat_ms,tests,devices,geometry
0,4100.250000,1852.5000,26.500000,1,1,"POLYGON ((-160.02686 70.64359, -160.02136 70.6..."
1,9195.000000,3347.0000,43.000000,1,1,"POLYGON ((-160.03235 70.63995, -160.02686 70.6..."
2,1898.125000,878.0625,11.187500,2,1,"POLYGON ((-160.04333 70.63631, -160.03784 70.6..."
3,7384.000000,3868.0000,65.000000,1,1,"POLYGON ((-160.03784 70.63631, -160.03235 70.6..."
4,8895.000000,3429.0000,43.000000,2,2,"POLYGON ((-160.02686 70.64177, -160.02136 70.6..."
...,...,...,...,...,...,...
9059732,5461.333333,1559.0000,20.777778,1,1,"POLYGON ((169.4696 -46.55886, 169.4751 -46.558..."
9059733,179.500000,247.0000,7.500000,1,1,"POLYGON ((169.57947 -46.56264, 169.58496 -46.5..."
9059734,4859.666667,2125.0000,15.000000,1,1,"POLYGON ((170.1947 -46.07323, 170.2002 -46.073..."
9059735,2115.250000,1121.1875,2.937500,3,2,"POLYGON ((170.1947 -46.07704, 170.2002 -46.077..."
9059736,5222.000000,5880.5000,6.500000,1,1,"POLYGON ((3.39478 -80.68801, 3.40027 -80.68801..."

In [5]:
# Convert VIIRS longitude/latitude to GeoDataFrame
Viirs = gpd.GeoDataFrame(
    Viirs, geometry=gpd.points_from_xy(Viirs.longitude, Viirs.latitude)
)

Viirs

         longitude   latitude  light_intensity                     geometry
0       -53.133333 -22.645834         0.001105  POINT (-53.13333 -22.64583)
1       -53.133333 -22.641667         0.001325  POINT (-53.13333 -22.64167)
2       -53.133333 -22.637500         0.001348   POINT (-53.13333 -22.6375)
3       -53.129167 -22.650000         0.001204     POINT (-53.12917 -22.65)
4       -53.129167 -22.645834         0.001163  POINT (-53.12917 -22.64583)
...            ...        ...              ...                          ...
4219474 -37.354166 -11.595833         0.001277  POINT (-37.35417 -11.59583)
4219475 -37.354166 -11.591667         0.001217  POINT (-37.35417 -11.59167)
4219476 -37.354166 -11.587500         0.001300   POINT (-37.35417 -11.5875)
4219477 -37.354166 -11.583333         0.001065  POINT (-37.35417 -11.58333)
4219478 -37.354166 -11.579167         0.000961  POINT (-37.35417 -11.57917)

[4219479 rows x 4 columns]

In [6]:
join_df = gpd.sjoin(Viirs, ookla_df, how='inner', predicate='intersects')
join_df.head()

,longitude,latitude,light_intensity,geometry,index_right,avg_d_kbps,avg_u_kbps,avg_lat_ms,tests,devices
120,-53.087500,-22.662500,0.009948,POINT (-53.0875 -22.6625),8380836,2554.0,2.0,28.0,2,1
160,-53.079167,-22.654167,0.001441,POINT (-53.07917 -22.65417),8380938,4846.5,507.0,34.5,1,1
161,-53.079167,-22.650000,0.001429,POINT (-53.07917 -22.65),8380938,4846.5,507.0,34.5,1,1
169,-53.079167,-22.616667,0.001418,POINT (-53.07917 -22.61667),8380935,5534.0,18846.0,29.0,1,1
182,-53.075000,-22.654167,0.001453,POINT (-53.075 -22.65417),8380938,4846.5,507.0,34.5,1,1

In [7]:
join_df.shape

(177534, 10)

In [8]:
join_df.to_csv('Ookla_Viirs.csv', index=False)