In [1]:
import pandas as pd

In [2]:
# Load VIIRS_cleaned data
viirs_cleaned_agg_df = pd.read_csv('viirs_20_cleaned.csv')

In [3]:
viirs_cleaned_agg_df

         state  longitude   latitude  light_intensity  year  observations
0        bahia -46.600000 -11.295833         0.340000  2020             3
1        bahia -46.600000 -11.291667         0.240000  2020             3
2        bahia -46.600000 -11.287500         0.303333  2020             3
3        bahia -46.600000 -11.283333         0.296667  2020             3
4        bahia -46.600000 -11.279167         0.290000  2020             2
...        ...        ...        ...              ...   ...           ...
4219474    sao -44.241667 -22.716667         0.260000  2020             3
4219475    sao -44.241667 -22.712500         0.260000  2020             3
4219476    sao -44.241667 -22.708334         0.266667  2020             3
4219477    sao -44.241667 -22.704167         0.333333  2020             3
4219478    sao -44.241667 -22.700000         0.353333  2020             3

[4219479 rows x 6 columns]

In [4]:
# Aggregate data by state, longitude, and latitude
viirs_aggregated = viirs_cleaned_agg_df.groupby(['state', 'longitude', 'latitude'], as_index=False).agg({
    'light_intensity': 'mean',  # Average light intensity
    # 'radiance_pct_change': 'mean',  # Average radiance percentage change
    'year': 'first',  # Keep the year (same for the group)
    'month': 'count'  # Count occurrences (should be 3 for Q1 2020)
})

# Rename columns for clarity
viirs_aggregated.rename(columns={'month': 'observations'}, inplace=True)

print(viirs_aggregated)

KeyError: "Column(s) ['month'] do not exist"

In [12]:
test = viirs_cleaned_agg_df['observations'] == 12
viirs_cleaned_agg_df[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 11
viirs_aggregated[test].value_counts().sum()

276276

In [ ]:
test = viirs_aggregated['observations'] == 10
viirs_aggregated[test].value_counts().sum()

229

In [ ]:
test = viirs_aggregated['observations'] == 9
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 8
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 7
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 6
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 5
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 4
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 3
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 2
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
test = viirs_aggregated['observations'] == 1
viirs_aggregated[test].value_counts().sum()

0

In [ ]:
viirs_adjust = viirs_aggregated.copy()

viirs_adjust['light_intensity'] = viirs_adjust['light_intensity'] / viirs_adjust['observations']

Viirs_avg = viirs_adjust.groupby(['longitude', 'latitude'], as_index=False).agg({
    'light_intensity': 'mean'
})

Viirs_avg.head()

   longitude   latitude  light_intensity
0 -53.133333 -25.341667              0.0
1 -53.133333 -25.337500              0.0
2 -53.133333 -25.333334              0.0
3 -53.133333 -25.329167              0.0
4 -53.133333 -25.325000              0.0

In [ ]:
Viirs_avg.describe()

          longitude      latitude  light_intensity
count  8.551005e+06  8.551005e+06     8.551005e+06
mean  -4.424817e+01 -1.699890e+01     4.095522e-02
std    4.050043e+00  5.029127e+00     2.748533e-01
min   -5.313333e+01 -2.534167e+01     0.000000e+00
25%   -4.654167e+01 -2.180417e+01     0.000000e+00
50%   -4.412083e+01 -1.659167e+01     0.000000e+00
75%   -4.111667e+01 -1.257917e+01     2.604167e-02
max   -3.735417e+01 -8.570833e+00     8.514049e+01

In [ ]:
Viirs_avg.to_csv('viirs_20_cleaned_agg.csv', index=False)

In [16]:
df = pd.read_csv('viirs_20_cleaned_agg.csv')
df.head()

   longitude   latitude  light_intensity
0 -53.133333 -25.341667              0.0
1 -53.133333 -25.337500              0.0
2 -53.133333 -25.333334              0.0
3 -53.133333 -25.329167              0.0
4 -53.133333 -25.325000              0.0

In [ ]:
df_clean = df[df['light_intensity'] > 0]

df_clean.to_csv('viirs_20_cleaned_agg.csv', index=False)

In [18]:
df_clean.head()

      longitude   latitude  light_intensity
647  -53.133333 -22.645834         0.023611
648  -53.133333 -22.641667         0.023750
649  -53.133333 -22.637500         0.023194
1975 -53.129167 -22.650000         0.023542
1976 -53.129167 -22.645834         0.024028

In [20]:
df_clean.shape

(4219479, 3)

In [19]:
df_clean.describe()

          longitude      latitude  light_intensity
count  4.219479e+06  4.219479e+06     4.219479e+06
mean  -4.386095e+01 -1.596449e+01     8.299800e-02
std    3.819068e+00  5.001738e+00     3.867884e-01
min   -5.313333e+01 -2.533750e+01     6.597222e-03
25%   -4.712917e+01 -2.162083e+01     2.291667e-02
50%   -4.317083e+01 -1.401667e+01     2.618056e-02
75%   -4.057500e+01 -1.173333e+01     3.472222e-02
max   -3.735417e+01 -8.570833e+00     8.514049e+01