In [1]:
import pandas as pd
import os

In [16]:

# csv_folder = r"F:\Economic2019"

# output_file = r"viirs_Merged.csv"


# csv_files = [
#     "ViirsBahiaMerged.csv",
#     "ViirsRioMerged.csv",
#     "ViirsSaoMerged.csv"
# ]

# dataframes = []
# for file in csv_files:
#     file_path = os.path.join(csv_folder, file)
#     df = pd.read_csv(file_path)
#     dataframes.append(df)

# merged_data = pd.concat(dataframes, ignore_index=True)

# merged_data.to_csv(output_file, index=False)

# print(f"Merged dataset saved to {output_file}")

In [17]:
df = pd.read_csv(r"F:\Economic2019\viirs_Merged.csv") ## change path according to your pc
df.head()

   longitude  latitude  light_intensity  state  year  month
0 -46.604167 -8.570833              0.0  bahia  2019      1
1 -46.600000 -8.570833              0.0  bahia  2019      1
2 -46.595833 -8.570833              0.0  bahia  2019      1
3 -46.591667 -8.570833              0.0  bahia  2019      1
4 -46.587500 -8.570833              0.0  bahia  2019      1

In [18]:
df.shape

(103566084, 6)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.isna().sum()

longitude          0
latitude           0
light_intensity    0
state              0
year               0
month              0
dtype: int64

In [21]:
invalid_corrdinates = df[(df['longitude'] < -180) | (df['longitude'] > 180) | (df['latitude'] < -90) | (df['latitude'] > 90)]
print(invalid_corrdinates)

Empty DataFrame
Columns: [longitude, latitude, light_intensity, state, year, month]
Index: []

In [22]:
df['state'] = df['state'].str.strip().str.lower()

In [23]:
df = df[df['light_intensity'] >= 0]

In [24]:
df.shape

(103511997, 6)

In [28]:
Viirs = df.groupby(['state', 'longitude', 'latitude'], as_index=False).agg({
    'light_intensity': 'mean',
    'year': 'first',
    'month': 'count'
})
Viirs.rename(columns={'month': 'observations'}, inplace=True)
print(Viirs)

         state  longitude   latitude  light_intensity  year  observations
0        bahia -46.604167 -18.316667              0.0  2019            12
1        bahia -46.604167 -18.312500              0.0  2019            12
2        bahia -46.604167 -18.308333              0.0  2019            12
3        bahia -46.604167 -18.304167              0.0  2019            12
4        bahia -46.604167 -18.300000              0.0  2019            12
...        ...        ...        ...              ...   ...           ...
8630502    sao -44.241667 -19.825000              0.0  2019            12
8630503    sao -44.241667 -19.820833              0.0  2019            12
8630504    sao -44.241667 -19.816667              0.0  2019            12
8630505    sao -44.241667 -19.812500              0.0  2019            12
8630506    sao -44.241667 -19.808333              0.0  2019            12

[8630507 rows x 6 columns]

In [33]:
Viirss = Viirs.copy()
Viirss['light_intensity'] = Viirss['light_intensity'] / Viirss['observations']
Viirs_avg = df.groupby(['longitude', 'latitude'], as_index=False).agg({
    'light_intensity': 'mean'
})
print(Viirs_avg.head())

   longitude   latitude  light_intensity
0 -53.133333 -25.341667              0.0
1 -53.133333 -25.337500              0.0
2 -53.133333 -25.333334              0.0
3 -53.133333 -25.329167              0.0
4 -53.133333 -25.325000              0.0

In [34]:
Viirs_avg.shape

(8551005, 3)

In [35]:
Viirs_avg.describe()

          longitude      latitude  light_intensity
count  8.551005e+06  8.551005e+06     8.551005e+06
mean  -4.424817e+01 -1.699890e+01     3.205360e-03
std    4.050043e+00  5.029127e+00     2.507833e-02
min   -5.313333e+01 -2.534167e+01     0.000000e+00
25%   -4.654167e+01 -2.180417e+01     0.000000e+00
50%   -4.412083e+01 -1.659167e+01     0.000000e+00
75%   -4.111667e+01 -1.257917e+01     1.423611e-03
max   -3.735417e+01 -8.570833e+00     6.546962e+00

In [36]:
output_path = r"F:\Economic2019\Viirs_Merged_Cleaned.csv"
Viirs_avg.to_csv(output_path,index=False)

In [2]:
df = pd.read_csv('Viirs_Merged_Cleaned.csv')
df = df[df['light_intensity'] > 0]
df.shape
output_path = r"F:\Economic2019\Viirs_Merged_Cleaned.csv"
df.to_csv(output_path,index=False)